version: '3'

services:
  workxpert:
    image: pradyumnacharate1/workxpert
    env_file: ./config/config.env
    ports:
      - "3000:5000"
    depends_on:
      - mongo
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "3001:27017"